# Generated by Django 4.2.4 on 2023-08-19 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_alter_publication_author_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='publication',
            new_name='publications',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comment_text',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.CharField(default=None, max_length=225),
        ),
    ]
