# Generated by Django 4.2.4 on 2023-08-19 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0005_rename_publication_comment_publications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='publications',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.publication'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
