# Generated by Django 4.2.4 on 2023-08-19 22:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_alter_comment_publications_alter_publication_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='comment',
            name='publications',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='login.publication'),
        ),
    ]
