# Generated by Django 4.2.4 on 2023-08-19 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_publication_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='slug',
        ),
    ]
