# Generated by Django 4.2.4 on 2023-08-20 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_comment_active_comment_created_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='active',
        ),
    ]
