# Generated by Django 4.2.4 on 2023-08-20 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_remove_comment_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='publications',
        ),
        migrations.AddField(
            model_name='comment',
            name='publication',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.publication'),
            preserve_default=False,
        ),
    ]
