# Generated by Django 4.2.4 on 2023-08-22 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_comment_active_alter_comment_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
