# Generated by Django 4.2.4 on 2023-08-22 22:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0015_remove_publication_likes_publication_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='likes_C',
            field=models.ManyToManyField(blank=True, related_name='likes_C', to=settings.AUTH_USER_MODEL),
        ),
    ]
