# Generated by Django 4.2.4 on 2023-08-25 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0019_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
