# Generated by Django 4.2.4 on 2023-08-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0024_profile_image_back_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_image',
            name='back_image',
            field=models.ImageField(blank=True, null=True, upload_to='login/media/back_image'),
        ),
    ]
